# Generated by Django 5.0.2 on 2024-03-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuingdetail',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
