# Generated by Django 5.0.2 on 2024-03-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_app', '0002_alter_queuingdetail_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messaage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itmessage', models.CharField(max_length=500)),
                ('user_reply', models.CharField(max_length=500)),
                ('Que_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queuing_app.queuingdetail')),
            ],
        ),
    ]
