# Generated by Django 5.0.2 on 2024-03-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_app', '0004_remove_messaage_user_reply_reply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messaage',
            new_name='Message',
        ),
    ]
