# Generated by Django 5.0.2 on 2024-04-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_app', '0006_message_timestamp_reply_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
