# Generated by Django 5.0.2 on 2024-03-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
