# Generated by Django 5.0.2 on 2024-03-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='ICTO_asdfassdsds', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
