# Generated by Django 5.0.2 on 2024-04-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.CharField(default='wala', max_length=100),
        ),
    ]
