# Generated by Django 5.0.2 on 2024-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_department_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='department_optional',
            field=models.IntegerField(default=404),
        ),
    ]
