# Generated by Django 5.0.2 on 2024-04-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useraccount_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='department_optional',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_ITstaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
