# Generated by Django 5.0.2 on 2024-03-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_department_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('voucher_code', models.IntegerField()),
                ('details', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('accounting_approval', models.BooleanField()),
                ('mayor_approval', models.BooleanField()),
                ('treasury_approval', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
    ]
