# Generated by Django 5.0.2 on 2024-04-03 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetail',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
