# Generated by Django 5.0.2 on 2024-04-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_voucherdetail_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdetail',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
