# Generated by Django 5.0.2 on 2024-04-16 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraccount_department_optional'),
        ('budget_app', '0003_alter_voucherdetail_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBugetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_budget', models.IntegerField()),
                ('datetime', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
    ]
