# Generated by Django 5.0.2 on 2024-04-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_alter_departmentbugetdetails_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentbugetdetails',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
